[project]
name = "test-task-py-api"
version = "0.1.0"
description = "Test task utilizing FastAPI to process technical support requests."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.0",
    "huggingface-hub>=0.33.2",
]
